INSERT INTO dbo.Categoria VALUES (1, 'RPG')
INSERT INTO dbo.Categoria VALUES (2, 'Corrida')
INSERT INTO dbo.Categoria VALUES (3, 'Aventura')
INSERT INTO dbo.Categoria VALUES (4, 'Luta')
INSERT INTO dbo.Categoria VALUES (5, 'Esporte')

INSERT INTO dbo.Selo VALUES (1, 'Bronze')
INSERT INTO dbo.Selo VALUES (2, 'Prata')
INSERT INTO dbo.Selo VALUES (3, 'Ouro')

INSERT INTO dbo.Jogo VALUES ('Chrono Trigger', 'Descricao do Jogo' ,60,1, null, 1)
INSERT INTO dbo.Jogo VALUES ('Top Gear', 'Descricao do Jogo' ,20,2, null, 1)
INSERT INTO dbo.Jogo VALUES ('Megaman X', 'Descricao do Jogo' ,40,3, null, 1)
INSERT INTO dbo.Jogo VALUES ('Super Metroid', 'Descricao do Jogo' ,35,3, null, 1)
INSERT INTO dbo.Jogo VALUES ('Donkey Kong Country', 'Descricao do Jogo' ,25,3, null, 1)
INSERT INTO dbo.Jogo VALUES ('Super Mario Kart', 'Descricao do Jogo' ,40,2, null, 1)
INSERT INTO dbo.Jogo VALUES ('Super Street Fighter', 'Descricao do Jogo' ,25,4, null, 1)
INSERT INTO dbo.Jogo VALUES ('Mortal Kombat 2', 'Descricao do Jogo' ,37,4, null, 1)
INSERT INTO dbo.Jogo VALUES ('Killer Instinct', 'Descricao do Jogo' ,18,4, null, 1)
INSERT INTO dbo.Jogo VALUES ('Final Fight', 'Descricao do Jogo' ,12,3, null, 1)
INSERT INTO dbo.Jogo VALUES ('Super Mario 1', 'Descricao do Jogo' ,70,1, null, 1)
INSERT INTO dbo.Jogo VALUES ('Aladdin', 'Descricao do Jogo' ,16,3, null, 1)
INSERT INTO dbo.Jogo VALUES ('Rock ''n Roll Racing', 'Descricao do Jogo' ,22,2, null, 1)
INSERT INTO dbo.Jogo VALUES ('Zelda: A link to the past', 'Descricao do Jogo' ,110,3, null, 1)
INSERT INTO dbo.Jogo VALUES ('Final Fantasy VI', 'Descricao do Jogo' ,30.5,1, null, 1)
INSERT INTO dbo.Jogo VALUES ('International Super Star Soccer Deluxe', 'Descricao do Jogo' ,45,5, null, 1)
INSERT INTO dbo.Jogo VALUES ('Contra III', 'Descricao do Jogo' ,28,3, null, 1)
INSERT INTO dbo.Jogo VALUES ('Sunset Riders', 'Descricao do Jogo' ,37.9,3, null, 1)
INSERT INTO dbo.Jogo VALUES ('Goof Troop', 'Descricao do Jogo' ,41.9,3, null, 1)
INSERT INTO dbo.Jogo VALUES ('Mickey to Donald: Magical Adventure 3', 'Descricao do Jogo' ,32.9,3, null, 1)